use crate::params::decode_constants;
use crate::poseidon;
use starkom_koalabear::KB as Scalar;
use std::sync::LazyLock;

/// Poseidon configuration for the KoalaBear field.
pub struct KoalaBearConfig<const T: usize> {}

impl poseidon::Config<Scalar, 24> for KoalaBearConfig<24> {
    fn num_full_rounds() -> usize {
        4
    }

    fn num_partial_rounds() -> usize {
        23
    }

    fn get_round_constants() -> &'static [Scalar] {
        static ROUND_CONSTANTS: LazyLock<[Scalar; 744]> = LazyLock::new(|| {
            let bytes = include_bytes!("../params/koalabear/arc_t24.bin");
            decode_constants::<Scalar, 744>(bytes)
        });
        &*ROUND_CONSTANTS
    }

    fn get_mds_matrix() -> &'static [Scalar] {
        static MATRIX: LazyLock<[Scalar; 576]> = LazyLock::new(|| {
            let bytes = include_bytes!("../params/koalabear/mds_t24.bin");
            decode_constants::<Scalar, 576>(bytes)
        });
        &*MATRIX
    }
}

impl poseidon::Config<Scalar, 32> for KoalaBearConfig<32> {
    fn num_full_rounds() -> usize {
        4
    }

    fn num_partial_rounds() -> usize {
        31
    }

    fn get_round_constants() -> &'static [Scalar] {
        static ROUND_CONSTANTS: LazyLock<[Scalar; 1248]> = LazyLock::new(|| {
            let bytes = include_bytes!("../params/koalabear/arc_t32.bin");
            decode_constants::<Scalar, 1248>(bytes)
        });
        &*ROUND_CONSTANTS
    }

    fn get_mds_matrix() -> &'static [Scalar] {
        static MATRIX: LazyLock<[Scalar; 1024]> = LazyLock::new(|| {
            let bytes = include_bytes!("../params/koalabear/mds_t32.bin");
            decode_constants::<Scalar, 1024>(bytes)
        });
        &*MATRIX
    }
}

/// Poseidon configuration for KoalaBear with T=24.
pub type KoalaBearConfig24 = KoalaBearConfig<24>;

/// Poseidon configuration for KoalaBear with T=32.
pub type KoalaBearConfig32 = KoalaBearConfig<32>;

#[cfg(test)]
mod tests {
    use super::*;
    use starkom_koalabear::from_const;

    fn hash_t24(inputs: impl IntoIterator<Item = Scalar>) -> [Scalar; 16] {
        poseidon::hash::<KoalaBearConfig24, Scalar, 24, 16, 8>(inputs)
    }

    fn hash_t24_0(inputs: impl IntoIterator<Item = Scalar>) -> Scalar {
        poseidon::hash0::<KoalaBearConfig24, Scalar, 24, 16, 8>(inputs)
    }

    fn hash_t32(inputs: impl IntoIterator<Item = Scalar>) -> [Scalar; 24] {
        poseidon::hash::<KoalaBearConfig32, Scalar, 32, 24, 8>(inputs)
    }

    fn hash_t32_0(inputs: impl IntoIterator<Item = Scalar>) -> Scalar {
        poseidon::hash0::<KoalaBearConfig32, Scalar, 32, 24, 8>(inputs)
    }

    fn parse_scalar(s: &'static str) -> Scalar {
        s.parse().unwrap()
    }

    #[test]
    fn test_permutation_t24() {
        assert_eq!(
            poseidon::permutation::<KoalaBearConfig24, Scalar, 24>([
                from_const(0),
                from_const(1),
                from_const(2),
                from_const(3),
                from_const(4),
                from_const(5),
                from_const(6),
                from_const(7),
                from_const(8),
                from_const(9),
                from_const(10),
                from_const(11),
                from_const(12),
                from_const(13),
                from_const(14),
                from_const(15),
                from_const(16),
                from_const(17),
                from_const(18),
                from_const(19),
                from_const(20),
                from_const(21),
                from_const(22),
                from_const(23),
            ]),
            [
                parse_scalar("0x20c420b9"),
                parse_scalar("0x13ee7831"),
                parse_scalar("0x1664a5fe"),
                parse_scalar("0x61b8a9da"),
                parse_scalar("0x62c0a36b"),
                parse_scalar("0x6686aa16"),
                parse_scalar("0x086b196f"),
                parse_scalar("0x2ba9a06e"),
                parse_scalar("0x48e393fa"),
                parse_scalar("0x40e4aa30"),
                parse_scalar("0x5afc6000"),
                parse_scalar("0x5c9bd903"),
                parse_scalar("0x3d866242"),
                parse_scalar("0x44fb43ec"),
                parse_scalar("0x4fd48650"),
                parse_scalar("0x45c361f2"),
                parse_scalar("0x5087cccd"),
                parse_scalar("0x0c28329f"),
                parse_scalar("0x58fc4353"),
                parse_scalar("0x1fa8695a"),
                parse_scalar("0x4a026a9d"),
                parse_scalar("0x3e0c59ec"),
                parse_scalar("0x3be00b5d"),
                parse_scalar("0x687cd26e"),
            ]
        );
    }

    #[test]
    fn test_permutation_t32() {
        assert_eq!(
            poseidon::permutation::<KoalaBearConfig32, Scalar, 32>([
                from_const(0),
                from_const(1),
                from_const(2),
                from_const(3),
                from_const(4),
                from_const(5),
                from_const(6),
                from_const(7),
                from_const(8),
                from_const(9),
                from_const(10),
                from_const(11),
                from_const(12),
                from_const(13),
                from_const(14),
                from_const(15),
                from_const(16),
                from_const(17),
                from_const(18),
                from_const(19),
                from_const(20),
                from_const(21),
                from_const(22),
                from_const(23),
                from_const(24),
                from_const(25),
                from_const(26),
                from_const(27),
                from_const(28),
                from_const(29),
                from_const(30),
                from_const(31),
            ]),
            [
                parse_scalar("0x2cd28abd"),
                parse_scalar("0x4b7e0de6"),
                parse_scalar("0x1c28010b"),
                parse_scalar("0x341a4215"),
                parse_scalar("0x2730f966"),
                parse_scalar("0x6d5f6492"),
                parse_scalar("0x2da41e53"),
                parse_scalar("0x5b9553f8"),
                parse_scalar("0x40f3bd78"),
                parse_scalar("0x1847d418"),
                parse_scalar("0x3b40f194"),
                parse_scalar("0x61deec2d"),
                parse_scalar("0x268de447"),
                parse_scalar("0x4ff70519"),
                parse_scalar("0x0276d981"),
                parse_scalar("0x0ecd4498"),
                parse_scalar("0x5852c99b"),
                parse_scalar("0x0c0c5656"),
                parse_scalar("0x1a5d72b5"),
                parse_scalar("0x1556aa75"),
                parse_scalar("0x05df8f05"),
                parse_scalar("0x4e9c5eb7"),
                parse_scalar("0x669108c9"),
                parse_scalar("0x051bc5f5"),
                parse_scalar("0x5d193fdf"),
                parse_scalar("0x1fc5ddac"),
                parse_scalar("0x478e26aa"),
                parse_scalar("0x78fe0af3"),
                parse_scalar("0x40b6dd16"),
                parse_scalar("0x6cc4f791"),
                parse_scalar("0x77e872fe"),
                parse_scalar("0x6112c017"),
            ]
        );
    }

    #[test]
    fn test_hash_t24_1() {
        assert_eq!(
            hash_t24([from_const(42)]),
            [
                parse_scalar("0x16203a99"),
                parse_scalar("0x675ad6f6"),
                parse_scalar("0x72fc45e1"),
                parse_scalar("0x39dc9595"),
                parse_scalar("0x11875376"),
                parse_scalar("0x7cc6069c"),
                parse_scalar("0x15b57f11"),
                parse_scalar("0x408936e8"),
                parse_scalar("0x3d45d792"),
                parse_scalar("0x541b3686"),
                parse_scalar("0x509a4eaa"),
                parse_scalar("0x5da73d2c"),
                parse_scalar("0x0080016c"),
                parse_scalar("0x1cb0a94a"),
                parse_scalar("0x6dea097c"),
                parse_scalar("0x074a0511"),
            ]
        );
        assert_eq!(hash_t24_0([from_const(42)]), parse_scalar("0x16203a99"));
    }

    #[test]
    fn test_hash_t24_2() {
        assert_eq!(
            hash_t24([from_const(12), from_const(34)]),
            [
                parse_scalar("0x682ff547"),
                parse_scalar("0x68012e80"),
                parse_scalar("0x3d02790d"),
                parse_scalar("0x668170a9"),
                parse_scalar("0x639e0cff"),
                parse_scalar("0x02064fca"),
                parse_scalar("0x2be6145e"),
                parse_scalar("0x27c846ed"),
                parse_scalar("0x6d88bcda"),
                parse_scalar("0x08ba3e90"),
                parse_scalar("0x5c6f780e"),
                parse_scalar("0x2c0471c7"),
                parse_scalar("0x3d560672"),
                parse_scalar("0x03dc2b92"),
                parse_scalar("0x64a6c1bb"),
                parse_scalar("0x083e63ae"),
            ]
        );
        assert_eq!(
            hash_t24_0([from_const(12), from_const(34)]),
            parse_scalar("0x682ff547")
        );
    }

    #[test]
    fn test_hash_t24_16() {
        assert_eq!(
            hash_t24([
                from_const(0),
                from_const(1),
                from_const(2),
                from_const(3),
                from_const(4),
                from_const(5),
                from_const(6),
                from_const(7),
                from_const(8),
                from_const(9),
                from_const(10),
                from_const(11),
                from_const(12),
                from_const(13),
                from_const(14),
                from_const(15),
            ]),
            [
                parse_scalar("0x3cbc6d5c"),
                parse_scalar("0x3efc8c2b"),
                parse_scalar("0x4c2b7b2c"),
                parse_scalar("0x4996b827"),
                parse_scalar("0x6d7b064c"),
                parse_scalar("0x1fe33565"),
                parse_scalar("0x6886a23b"),
                parse_scalar("0x6ecb7a72"),
                parse_scalar("0x3a3cf295"),
                parse_scalar("0x11f070e0"),
                parse_scalar("0x3b464b06"),
                parse_scalar("0x237378d9"),
                parse_scalar("0x1ea544eb"),
                parse_scalar("0x5f12ea4a"),
                parse_scalar("0x255ad713"),
                parse_scalar("0x57b6f3df"),
            ]
        );
        assert_eq!(
            hash_t24_0([
                from_const(0),
                from_const(1),
                from_const(2),
                from_const(3),
                from_const(4),
                from_const(5),
                from_const(6),
                from_const(7),
                from_const(8),
                from_const(9),
                from_const(10),
                from_const(11),
                from_const(12),
                from_const(13),
                from_const(14),
                from_const(15),
            ]),
            parse_scalar("0x3cbc6d5c")
        );
    }

    #[test]
    fn test_hash_t24_17() {
        assert_eq!(
            hash_t24([
                from_const(0),
                from_const(1),
                from_const(2),
                from_const(3),
                from_const(4),
                from_const(5),
                from_const(6),
                from_const(7),
                from_const(8),
                from_const(9),
                from_const(10),
                from_const(11),
                from_const(12),
                from_const(13),
                from_const(14),
                from_const(15),
                from_const(16),
            ]),
            [
                parse_scalar("0x12db4aa5"),
                parse_scalar("0x0c3496d0"),
                parse_scalar("0x73458a62"),
                parse_scalar("0x10d47f48"),
                parse_scalar("0x008e13c1"),
                parse_scalar("0x759827cc"),
                parse_scalar("0x42680be9"),
                parse_scalar("0x3fc2112c"),
                parse_scalar("0x35d20a10"),
                parse_scalar("0x66b6c1a8"),
                parse_scalar("0x747381f8"),
                parse_scalar("0x6ecb26a6"),
                parse_scalar("0x71b7a5b6"),
                parse_scalar("0x5bbd3a9e"),
                parse_scalar("0x387ce5a4"),
                parse_scalar("0x16b48943"),
            ]
        );
        assert_eq!(
            hash_t24_0([
                from_const(0),
                from_const(1),
                from_const(2),
                from_const(3),
                from_const(4),
                from_const(5),
                from_const(6),
                from_const(7),
                from_const(8),
                from_const(9),
                from_const(10),
                from_const(11),
                from_const(12),
                from_const(13),
                from_const(14),
                from_const(15),
                from_const(16),
            ]),
            parse_scalar("0x12db4aa5")
        );
    }

    #[test]
    fn test_hash_t24_23() {
        assert_eq!(
            hash_t24([
                from_const(0),
                from_const(1),
                from_const(2),
                from_const(3),
                from_const(4),
                from_const(5),
                from_const(6),
                from_const(7),
                from_const(8),
                from_const(9),
                from_const(10),
                from_const(11),
                from_const(12),
                from_const(13),
                from_const(14),
                from_const(15),
                from_const(16),
                from_const(17),
                from_const(18),
                from_const(19),
                from_const(20),
                from_const(21),
                from_const(22),
            ]),
            [
                parse_scalar("0x6ff7c2fa"),
                parse_scalar("0x1c0d103c"),
                parse_scalar("0x2aef16be"),
                parse_scalar("0x03721307"),
                parse_scalar("0x43e01e85"),
                parse_scalar("0x3ea6243f"),
                parse_scalar("0x0397204a"),
                parse_scalar("0x172e60e2"),
                parse_scalar("0x43a8154e"),
                parse_scalar("0x7b4dc8d0"),
                parse_scalar("0x4af0974f"),
                parse_scalar("0x69036861"),
                parse_scalar("0x3c8be546"),
                parse_scalar("0x3c7fabf7"),
                parse_scalar("0x40ad7f48"),
                parse_scalar("0x634bacda"),
            ]
        );
        assert_eq!(
            hash_t24_0([
                from_const(0),
                from_const(1),
                from_const(2),
                from_const(3),
                from_const(4),
                from_const(5),
                from_const(6),
                from_const(7),
                from_const(8),
                from_const(9),
                from_const(10),
                from_const(11),
                from_const(12),
                from_const(13),
                from_const(14),
                from_const(15),
                from_const(16),
                from_const(17),
                from_const(18),
                from_const(19),
                from_const(20),
                from_const(21),
                from_const(22),
            ]),
            parse_scalar("0x6ff7c2fa")
        );
    }

    #[test]
    fn test_hash_t24_24() {
        assert_eq!(
            hash_t24([
                from_const(0),
                from_const(1),
                from_const(2),
                from_const(3),
                from_const(4),
                from_const(5),
                from_const(6),
                from_const(7),
                from_const(8),
                from_const(9),
                from_const(10),
                from_const(11),
                from_const(12),
                from_const(13),
                from_const(14),
                from_const(15),
                from_const(16),
                from_const(17),
                from_const(18),
                from_const(19),
                from_const(20),
                from_const(21),
                from_const(22),
                from_const(23),
            ]),
            [
                parse_scalar("0x617265ca"),
                parse_scalar("0x48452b65"),
                parse_scalar("0x7bcbebbc"),
                parse_scalar("0x1e757dfa"),
                parse_scalar("0x13ab75e4"),
                parse_scalar("0x7737ed87"),
                parse_scalar("0x15489104"),
                parse_scalar("0x3d373bc2"),
                parse_scalar("0x349fe5c6"),
                parse_scalar("0x7e28163f"),
                parse_scalar("0x53af722c"),
                parse_scalar("0x6015abd3"),
                parse_scalar("0x6e495b22"),
                parse_scalar("0x3a52372c"),
                parse_scalar("0x400167da"),
                parse_scalar("0x674c02db"),
            ]
        );
        assert_eq!(
            hash_t24_0([
                from_const(0),
                from_const(1),
                from_const(2),
                from_const(3),
                from_const(4),
                from_const(5),
                from_const(6),
                from_const(7),
                from_const(8),
                from_const(9),
                from_const(10),
                from_const(11),
                from_const(12),
                from_const(13),
                from_const(14),
                from_const(15),
                from_const(16),
                from_const(17),
                from_const(18),
                from_const(19),
                from_const(20),
                from_const(21),
                from_const(22),
                from_const(23),
            ]),
            parse_scalar("0x617265ca")
        );
    }

    #[test]
    fn test_hash_t24_25() {
        assert_eq!(
            hash_t24([
                from_const(0),
                from_const(1),
                from_const(2),
                from_const(3),
                from_const(4),
                from_const(5),
                from_const(6),
                from_const(7),
                from_const(8),
                from_const(9),
                from_const(10),
                from_const(11),
                from_const(12),
                from_const(13),
                from_const(14),
                from_const(15),
                from_const(16),
                from_const(17),
                from_const(18),
                from_const(19),
                from_const(20),
                from_const(21),
                from_const(22),
                from_const(23),
                from_const(24),
            ]),
            [
                parse_scalar("0x27492ed2"),
                parse_scalar("0x4bfd627d"),
                parse_scalar("0x07081f84"),
                parse_scalar("0x5551716c"),
                parse_scalar("0x606a4ad5"),
                parse_scalar("0x0d3b0acf"),
                parse_scalar("0x36cbdd7c"),
                parse_scalar("0x2d24dfa9"),
                parse_scalar("0x2ef2a669"),
                parse_scalar("0x2eef6827"),
                parse_scalar("0x5f484bac"),
                parse_scalar("0x1183d183"),
                parse_scalar("0x33cac7a1"),
                parse_scalar("0x2f1445c0"),
                parse_scalar("0x01da4877"),
                parse_scalar("0x2da76494"),
            ]
        );
        assert_eq!(
            hash_t24_0([
                from_const(0),
                from_const(1),
                from_const(2),
                from_const(3),
                from_const(4),
                from_const(5),
                from_const(6),
                from_const(7),
                from_const(8),
                from_const(9),
                from_const(10),
                from_const(11),
                from_const(12),
                from_const(13),
                from_const(14),
                from_const(15),
                from_const(16),
                from_const(17),
                from_const(18),
                from_const(19),
                from_const(20),
                from_const(21),
                from_const(22),
                from_const(23),
                from_const(24),
            ]),
            parse_scalar("0x27492ed2")
        );
    }

    #[test]
    fn test_hash_t32_1() {
        assert_eq!(
            hash_t32([from_const(42)]),
            [
                parse_scalar("0x124138c6"),
                parse_scalar("0x76b95d35"),
                parse_scalar("0x53035a87"),
                parse_scalar("0x367161fb"),
                parse_scalar("0x6663a034"),
                parse_scalar("0x4137c32d"),
                parse_scalar("0x18a7cedb"),
                parse_scalar("0x47b62a63"),
                parse_scalar("0x3b174224"),
                parse_scalar("0x4894746c"),
                parse_scalar("0x0004353f"),
                parse_scalar("0x21742617"),
                parse_scalar("0x55648fc8"),
                parse_scalar("0x73ab4f25"),
                parse_scalar("0x42d049ac"),
                parse_scalar("0x7d0b3bd7"),
                parse_scalar("0x7bf148a3"),
                parse_scalar("0x48369481"),
                parse_scalar("0x7469eb77"),
                parse_scalar("0x3a301ebf"),
                parse_scalar("0x1e99595f"),
                parse_scalar("0x309458ed"),
                parse_scalar("0x7bfe919e"),
                parse_scalar("0x2c6e2995"),
            ]
        );
        assert_eq!(hash_t32_0([from_const(42)]), parse_scalar("0x124138c6"));
    }

    #[test]
    fn test_hash_t32_2() {
        assert_eq!(
            hash_t32([from_const(12), from_const(34)]),
            [
                parse_scalar("0x3ca81acf"),
                parse_scalar("0x15096cdf"),
                parse_scalar("0x3d3f61f4"),
                parse_scalar("0x0315aa5a"),
                parse_scalar("0x50d7c9be"),
                parse_scalar("0x4b14c725"),
                parse_scalar("0x2261eaf8"),
                parse_scalar("0x0adc5a39"),
                parse_scalar("0x41a527a1"),
                parse_scalar("0x7a856336"),
                parse_scalar("0x669fab74"),
                parse_scalar("0x5d7ed6c6"),
                parse_scalar("0x51878b10"),
                parse_scalar("0x5137c12f"),
                parse_scalar("0x1495784f"),
                parse_scalar("0x3e3b4066"),
                parse_scalar("0x63e5ad32"),
                parse_scalar("0x2468829f"),
                parse_scalar("0x58e282b6"),
                parse_scalar("0x2e6a84e5"),
                parse_scalar("0x2ca88ba1"),
                parse_scalar("0x438bd9d7"),
                parse_scalar("0x1842a516"),
                parse_scalar("0x142a60f5"),
            ]
        );
        assert_eq!(
            hash_t32_0([from_const(12), from_const(34)]),
            parse_scalar("0x3ca81acf")
        );
    }

    #[test]
    fn test_hash_t32_24() {
        assert_eq!(
            hash_t32([
                from_const(0),
                from_const(1),
                from_const(2),
                from_const(3),
                from_const(4),
                from_const(5),
                from_const(6),
                from_const(7),
                from_const(8),
                from_const(9),
                from_const(10),
                from_const(11),
                from_const(12),
                from_const(13),
                from_const(14),
                from_const(15),
                from_const(16),
                from_const(17),
                from_const(18),
                from_const(19),
                from_const(20),
                from_const(21),
                from_const(22),
                from_const(23),
            ]),
            [
                parse_scalar("0x2669e81d"),
                parse_scalar("0x37275f95"),
                parse_scalar("0x334ed52d"),
                parse_scalar("0x0da08077"),
                parse_scalar("0x546df638"),
                parse_scalar("0x0e142ef5"),
                parse_scalar("0x2554cf75"),
                parse_scalar("0x7aeabbcf"),
                parse_scalar("0x16daecae"),
                parse_scalar("0x01aadbe8"),
                parse_scalar("0x4623b19a"),
                parse_scalar("0x607faa1b"),
                parse_scalar("0x108e93f7"),
                parse_scalar("0x7e1153a0"),
                parse_scalar("0x450b79c8"),
                parse_scalar("0x15d0bdc9"),
                parse_scalar("0x487ec2bb"),
                parse_scalar("0x21f8dc0e"),
                parse_scalar("0x14f9f357"),
                parse_scalar("0x657ad505"),
                parse_scalar("0x15f440b7"),
                parse_scalar("0x27389ded"),
                parse_scalar("0x5ec33eba"),
                parse_scalar("0x77ae7dca"),
            ]
        );
        assert_eq!(
            hash_t32_0([
                from_const(0),
                from_const(1),
                from_const(2),
                from_const(3),
                from_const(4),
                from_const(5),
                from_const(6),
                from_const(7),
                from_const(8),
                from_const(9),
                from_const(10),
                from_const(11),
                from_const(12),
                from_const(13),
                from_const(14),
                from_const(15),
                from_const(16),
                from_const(17),
                from_const(18),
                from_const(19),
                from_const(20),
                from_const(21),
                from_const(22),
                from_const(23),
            ]),
            parse_scalar("0x2669e81d")
        );
    }

    #[test]
    fn test_hash_t32_25() {
        assert_eq!(
            hash_t32([
                from_const(0),
                from_const(1),
                from_const(2),
                from_const(3),
                from_const(4),
                from_const(5),
                from_const(6),
                from_const(7),
                from_const(8),
                from_const(9),
                from_const(10),
                from_const(11),
                from_const(12),
                from_const(13),
                from_const(14),
                from_const(15),
                from_const(16),
                from_const(17),
                from_const(18),
                from_const(19),
                from_const(20),
                from_const(21),
                from_const(22),
                from_const(23),
                from_const(24),
            ]),
            [
                parse_scalar("0x43300146"),
                parse_scalar("0x0806f638"),
                parse_scalar("0x688750b5"),
                parse_scalar("0x3cebd421"),
                parse_scalar("0x48f5a1ac"),
                parse_scalar("0x167b6a04"),
                parse_scalar("0x18da050c"),
                parse_scalar("0x37727f40"),
                parse_scalar("0x2e9038ec"),
                parse_scalar("0x4af1c7ad"),
                parse_scalar("0x6527807a"),
                parse_scalar("0x636018fb"),
                parse_scalar("0x45ee4954"),
                parse_scalar("0x2558227d"),
                parse_scalar("0x6238c54c"),
                parse_scalar("0x4d946b65"),
                parse_scalar("0x2ac34872"),
                parse_scalar("0x0ea840d4"),
                parse_scalar("0x3b47bded"),
                parse_scalar("0x4790cf2f"),
                parse_scalar("0x509707f8"),
                parse_scalar("0x22d5190a"),
                parse_scalar("0x34b652e2"),
                parse_scalar("0x4eaf206d"),
            ]
        );
        assert_eq!(
            hash_t32_0([
                from_const(0),
                from_const(1),
                from_const(2),
                from_const(3),
                from_const(4),
                from_const(5),
                from_const(6),
                from_const(7),
                from_const(8),
                from_const(9),
                from_const(10),
                from_const(11),
                from_const(12),
                from_const(13),
                from_const(14),
                from_const(15),
                from_const(16),
                from_const(17),
                from_const(18),
                from_const(19),
                from_const(20),
                from_const(21),
                from_const(22),
                from_const(23),
                from_const(24),
            ]),
            parse_scalar("0x43300146")
        );
    }

    #[test]
    fn test_hash_t32_31() {
        assert_eq!(
            hash_t32([
                from_const(0),
                from_const(1),
                from_const(2),
                from_const(3),
                from_const(4),
                from_const(5),
                from_const(6),
                from_const(7),
                from_const(8),
                from_const(9),
                from_const(10),
                from_const(11),
                from_const(12),
                from_const(13),
                from_const(14),
                from_const(15),
                from_const(16),
                from_const(17),
                from_const(18),
                from_const(19),
                from_const(20),
                from_const(21),
                from_const(22),
                from_const(23),
                from_const(24),
                from_const(25),
                from_const(26),
                from_const(27),
                from_const(28),
                from_const(29),
                from_const(30),
            ]),
            [
                parse_scalar("0x2928a1ce"),
                parse_scalar("0x622fa59f"),
                parse_scalar("0x0a8f6152"),
                parse_scalar("0x3ccf79d0"),
                parse_scalar("0x7ab31882"),
                parse_scalar("0x65c6d7c2"),
                parse_scalar("0x2d0b4f19"),
                parse_scalar("0x5bbadc84"),
                parse_scalar("0x73638bb7"),
                parse_scalar("0x57e6dd48"),
                parse_scalar("0x7dd6040c"),
                parse_scalar("0x238fa206"),
                parse_scalar("0x34c0ade1"),
                parse_scalar("0x76d109e0"),
                parse_scalar("0x22e3b187"),
                parse_scalar("0x4619cc20"),
                parse_scalar("0x5971a5bc"),
                parse_scalar("0x444989cd"),
                parse_scalar("0x22d1dc0a"),
                parse_scalar("0x1f7fe5b1"),
                parse_scalar("0x340a36b1"),
                parse_scalar("0x102c3e83"),
                parse_scalar("0x647ed19e"),
                parse_scalar("0x5ee20ca6"),
            ]
        );
        assert_eq!(
            hash_t32_0([
                from_const(0),
                from_const(1),
                from_const(2),
                from_const(3),
                from_const(4),
                from_const(5),
                from_const(6),
                from_const(7),
                from_const(8),
                from_const(9),
                from_const(10),
                from_const(11),
                from_const(12),
                from_const(13),
                from_const(14),
                from_const(15),
                from_const(16),
                from_const(17),
                from_const(18),
                from_const(19),
                from_const(20),
                from_const(21),
                from_const(22),
                from_const(23),
                from_const(24),
                from_const(25),
                from_const(26),
                from_const(27),
                from_const(28),
                from_const(29),
                from_const(30),
            ]),
            parse_scalar("0x2928a1ce")
        );
    }

    #[test]
    fn test_hash_t32_32() {
        assert_eq!(
            hash_t32([
                from_const(0),
                from_const(1),
                from_const(2),
                from_const(3),
                from_const(4),
                from_const(5),
                from_const(6),
                from_const(7),
                from_const(8),
                from_const(9),
                from_const(10),
                from_const(11),
                from_const(12),
                from_const(13),
                from_const(14),
                from_const(15),
                from_const(16),
                from_const(17),
                from_const(18),
                from_const(19),
                from_const(20),
                from_const(21),
                from_const(22),
                from_const(23),
                from_const(24),
                from_const(25),
                from_const(26),
                from_const(27),
                from_const(28),
                from_const(29),
                from_const(30),
                from_const(31),
            ]),
            [
                parse_scalar("0x33fb7eab"),
                parse_scalar("0x01effac1"),
                parse_scalar("0x274e2b70"),
                parse_scalar("0x672b815b"),
                parse_scalar("0x3aeaa84c"),
                parse_scalar("0x557d0634"),
                parse_scalar("0x196e5ff9"),
                parse_scalar("0x13971cd0"),
                parse_scalar("0x514ab220"),
                parse_scalar("0x5417c64f"),
                parse_scalar("0x0bf2d9db"),
                parse_scalar("0x5b86b2c1"),
                parse_scalar("0x20ef6d6b"),
                parse_scalar("0x34f9b91b"),
                parse_scalar("0x427c8b16"),
                parse_scalar("0x2168bc12"),
                parse_scalar("0x27e19c41"),
                parse_scalar("0x754ea2f6"),
                parse_scalar("0x7bb97f09"),
                parse_scalar("0x2cffdeb4"),
                parse_scalar("0x5b8e892d"),
                parse_scalar("0x295d8864"),
                parse_scalar("0x46e93683"),
                parse_scalar("0x27f0e4f7"),
            ]
        );
        assert_eq!(
            hash_t32_0([
                from_const(0),
                from_const(1),
                from_const(2),
                from_const(3),
                from_const(4),
                from_const(5),
                from_const(6),
                from_const(7),
                from_const(8),
                from_const(9),
                from_const(10),
                from_const(11),
                from_const(12),
                from_const(13),
                from_const(14),
                from_const(15),
                from_const(16),
                from_const(17),
                from_const(18),
                from_const(19),
                from_const(20),
                from_const(21),
                from_const(22),
                from_const(23),
                from_const(24),
                from_const(25),
                from_const(26),
                from_const(27),
                from_const(28),
                from_const(29),
                from_const(30),
                from_const(31),
            ]),
            parse_scalar("0x33fb7eab")
        );
    }

    #[test]
    fn test_hash_t32_33() {
        assert_eq!(
            hash_t32([
                from_const(0),
                from_const(1),
                from_const(2),
                from_const(3),
                from_const(4),
                from_const(5),
                from_const(6),
                from_const(7),
                from_const(8),
                from_const(9),
                from_const(10),
                from_const(11),
                from_const(12),
                from_const(13),
                from_const(14),
                from_const(15),
                from_const(16),
                from_const(17),
                from_const(18),
                from_const(19),
                from_const(20),
                from_const(21),
                from_const(22),
                from_const(23),
                from_const(24),
                from_const(25),
                from_const(26),
                from_const(27),
                from_const(28),
                from_const(29),
                from_const(30),
                from_const(31),
                from_const(32),
            ]),
            [
                parse_scalar("0x41a34e14"),
                parse_scalar("0x299a4cc1"),
                parse_scalar("0x3ebdb5e4"),
                parse_scalar("0x5c300b2d"),
                parse_scalar("0x0c7ee491"),
                parse_scalar("0x0d16cb78"),
                parse_scalar("0x757cd076"),
                parse_scalar("0x0159a359"),
                parse_scalar("0x250bbb48"),
                parse_scalar("0x74d72264"),
                parse_scalar("0x74df1f73"),
                parse_scalar("0x0067602d"),
                parse_scalar("0x59b6eee8"),
                parse_scalar("0x70bf88bf"),
                parse_scalar("0x7443dc01"),
                parse_scalar("0x4e989666"),
                parse_scalar("0x0757c1ef"),
                parse_scalar("0x3a023c44"),
                parse_scalar("0x64af3cbd"),
                parse_scalar("0x610ae2b8"),
                parse_scalar("0x5350655a"),
                parse_scalar("0x42bf4bad"),
                parse_scalar("0x4f2f5c47"),
                parse_scalar("0x282b07e5"),
            ]
        );
        assert_eq!(
            hash_t32_0([
                from_const(0),
                from_const(1),
                from_const(2),
                from_const(3),
                from_const(4),
                from_const(5),
                from_const(6),
                from_const(7),
                from_const(8),
                from_const(9),
                from_const(10),
                from_const(11),
                from_const(12),
                from_const(13),
                from_const(14),
                from_const(15),
                from_const(16),
                from_const(17),
                from_const(18),
                from_const(19),
                from_const(20),
                from_const(21),
                from_const(22),
                from_const(23),
                from_const(24),
                from_const(25),
                from_const(26),
                from_const(27),
                from_const(28),
                from_const(29),
                from_const(30),
                from_const(31),
                from_const(32),
            ]),
            parse_scalar("0x41a34e14")
        );
    }
}
